### ISSUE TITLE
Move README screenshot images to a screenshots/ directory

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon-services/service-node-red-hello-world#1]
Move the screenshot images to a screenshots/ directory.
I like `screenshots` better than `images` because we often talk about container images.  Let's not confuse learners with terminology that means very different things.

Edit the README.md file and change the links to the screenshots/ directory.

**Comment by yadavsairaj** [comment]
Hey @johnwalicki can you assign this task to me?

**Comment by johnwalicki** [comment]
Closed by https://github.com/open-horizon-services/service-node-red-hello-world/pull/6
